// One-shot generator for engine/src/guard/fixtures/guard-shared-block-verdicts.ts (#840).
//
// guard.fuzz.test.ts's differential test used to run the predecessor project's guard.py LIVE,
// every CI run, over a deterministic 1500-command corpus. That's paying rent on a Python runtime
// forever for a frozen oracle whose output over a FIXED corpus is constant. #840 captured the
// verdicts ONCE and deleted the vendored guard.py (fixtures/guard_py_snapshot/); the test now
// asserts guard.ts against the static table this script produced.
//
// This script is not part of the test run and needs no interpreter to be present for `npm test`
// to pass — it exists solely so a human can re-derive the fixture from a DELIBERATE future
// re-vendor of guard.py (a git operation, not a standing knob). To use it:
//
//   1. Obtain a fresh checkout of the predecessor project's guard.py (+ the two `__init__.py`
//      files that make `zeroday.loop.guard` importable), e.g. in a scratch directory laid out as:
//        <dir>/zeroday/__init__.py
//        <dir>/zeroday/loop/__init__.py
//        <dir>/zeroday/loop/guard.py
//   2. Run:
//        GUARD_PY_DIR=<dir> npx tsx engine/scripts/regen-guard-shared-block-fixture.ts
//   3. Review the diff to engine/src/guard/fixtures/guard-shared-block-verdicts.ts, note the new
//      guard.py provenance (commit/md5) in this script's regenerated header, and re-run
//      `npm --workspace engine test`.
//
// The corpus is imported from ./src/guard/fixtures/fuzz-corpus.ts — the SAME module the test
// imports — so the fixture this script writes is guaranteed to cover exactly the commands the
// test replays, with nothing hand-edited in between.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { generateFuzzCorpus, HAND_PICKED_SHARED_BLOCK_CASES } from "../src/guard/fixtures/fuzz-corpus.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_FILE = join(repoRoot, "src", "guard", "fixtures", "guard-shared-block-verdicts.ts");

const PY_DRIVER = `
import sys, json
from zeroday.loop.guard import guard_decision
data = json.load(sys.stdin)
out = [{"allow": (d := guard_decision("Bash", x["command"], x.get("cwd", "/repo"), {})).allow, "reason": d.reason} for x in data]
sys.stdout.write(json.dumps(out))
`;

interface PyDecision {
  allow: boolean;
  reason: string;
}

// A guard.py BLOCK reason on the surface sapwood also implements. Mirrors
// guard.fuzz.test.ts's isSharedBlock — the one-directional invariant `guard.ts ⊇ guard.py` uses
// nothing else, so only these rows are worth capturing.
function isSharedBlock(d: PyDecision): boolean {
  return !d.allow && (/opaque/i.test(d.reason) || d.reason.includes("类别C"));
}

function pythonBin(): string {
  for (const bin of ["python3", "python"]) {
    try {
      execFileSync(bin, ["--version"], { stdio: "ignore" });
      return bin;
    } catch {
      /* try next */
    }
  }
  throw new Error("no python3/python interpreter found — required only for this one-shot regen");
}

function main(): void {
  const guardPyDir = process.env.GUARD_PY_DIR;
  if (!guardPyDir) {
    throw new Error(
      "GUARD_PY_DIR is required: point it at a directory containing zeroday/loop/guard.py " +
        "(a fresh checkout of the predecessor project's guard). See this file's header.",
    );
  }
  const guardPyRoot = resolve(guardPyDir);
  const bin = pythonBin();

  const commands = [...generateFuzzCorpus(), ...HAND_PICKED_SHARED_BLOCK_CASES];
  const input = JSON.stringify(commands.map((command) => ({ command, cwd: "/repo" })));
  const out = execFileSync(bin, ["-c", PY_DRIVER], {
    input,
    env: { ...process.env, PYTHONPATH: guardPyRoot },
    maxBuffer: 64 * 1024 * 1024,
    encoding: "utf8",
  });
  const decisions = JSON.parse(out) as PyDecision[];
  if (decisions.length !== commands.length) {
    throw new Error(`guard.py returned ${decisions.length} decisions for ${commands.length} commands`);
  }

  const table = new Map<string, string>();
  for (let i = 0; i < commands.length; i++) {
    const d = decisions[i]!;
    if (isSharedBlock(d)) table.set(commands[i]!, d.reason);
  }

  const entries = [...table.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const body = entries.map(([command, reason]) => `  ${JSON.stringify(command)}: ${JSON.stringify(reason)},`).join("\n");

  const contents = `// GENERATED by scripts/regen-guard-shared-block-fixture.ts (#840) — do not hand-edit.
//
// Captured shared-block verdicts from a one-time run of the predecessor project's guard.py over
// the deterministic corpus (fixtures/fuzz-corpus.ts: generateFuzzCorpus() + HAND_PICKED_SHARED_BLOCK_CASES).
// "Shared-block" = guard.py denied with an opaque-construct or Category C (\`类别C\`) reason — the
// one-directional invariant guard.fuzz.test.ts's differential test checks: guard.ts must ALSO
// block every command that appears as a key here.
//
// To re-derive (a deliberate future re-vendor of guard.py, not a standing knob — see that
// script's header for the full procedure):
//   GUARD_PY_DIR=<fresh predecessor guard.py checkout> npx tsx engine/scripts/regen-guard-shared-block-fixture.ts
//
// Regenerated: ${new Date().toISOString().slice(0, 10)}
// guard.py source: predecessor project, see prior fixtures/guard_py_snapshot/SOURCE.md
//   (commit 7e3dbd6d85790ea41547a2d55a30fbe80f2ce5d2, snapshot HEAD 19b692b0de0ceb6fa139a467397d9884ad99a033,
//    md5 b0f694e975d9bca60a5581744e361575, 841 lines) — deleted by #840, this table is its distillate.
// Corpus size captured: ${commands.length} (${generateFuzzCorpus().length} generated + ${HAND_PICKED_SHARED_BLOCK_CASES.length} hand-picked)
// Shared-block rows kept: ${table.size}

/** command -> guard.py's shared-block reason string. */
export const GUARD_PY_SHARED_BLOCK_VERDICTS: Record<string, string> = {
${body}
};
`;

  writeFileSync(OUT_FILE, contents);
  // eslint-disable-next-line no-console
  console.log(`wrote ${table.size} shared-block verdicts (of ${commands.length} commands) to ${OUT_FILE}`);
}

main();
